create sequence movie_sequence start 1;
create sequence screening_sequence start 1;
create sequence cinema_sequence start 1;

CREATE TABLE if NOT EXISTS Movie(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name            varchar(255) not null,
  synopsis        varchar(255) not null,
  directed_by      varchar(255) not null,
  rated           varchar(255) not null,
  running_time     time,
  genre           varchar(255) not null,
  release_date     date,
  cast_and_crews  varchar(255) not null,
  poster          varchar(255) not null
);


CREATE TABLE if NOT EXISTS Screening(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  available_seats  varchar(255) not null,
  start_time       time,
  end_time         time,
  movie_date       date,
  movie_id         BIGINT);

CREATE TABLE if NOT EXISTS Cinema(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name            varchar(255) not null,
  screening_id     BIGINT,
  movie_id         BIGINT
);
