create sequence payment_sequence start 1;

CREATE TABLE if NOT EXISTS Payment(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  full_name      varchar(255) not null,
  email         varchar(255) not null,
  contact_detail    int,
  card_detail int,
  card_holder_name varchar(255),
  card_expiration int,
  card_code int,
  movie_Name            varchar(255),
  cinema_Name           varchar(255),
  screening_date        date,
  screening_start_time  time,
  screening_end_time    time,
  selected_seats        varchar(255),
  total_price           double precision
);