DROP TABLE MOVIE;
DROP TABLE SCREENING;

CREATE TABLE if NOT EXISTS Movie(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name            varchar(255) not null,
  synopsis        varchar(255) not null,
  directed_by      varchar(255) not null,
  rated           varchar(255) not null,
  running_time     time,
  genre           varchar(255) not null,
  release_date     date,
  cast_and_crews  varchar(255) not null,
  poster          varchar(255) not null
);

ALTER TABLE movie ADD COLUMN status varchar(255);
ALTER TABLE movie ADD COLUMN critics_rating decimal(3, 1);
ALTER TABLE movie ADD COLUMN audience_rating decimal(3, 1);
ALTER TABLE Movie ADD cinema_id int;
ALTER TABLE Movie ADD movie_id int not null;

CREATE TABLE if NOT EXISTS Screening(
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
  available_seats  varchar(255) not null,
  start_time       time,
  end_time         time,
  movie_date       date,
  movie_id         BIGINT
);

ALTER TABLE Screening ADD COLUMN cinema_id int;

--INSERT MOVIE
INSERT INTO MOVIE(name,synopsis,directed_by,rated,running_time,genre,release_date,cast_and_crews,poster,status,critics_rating,audience_rating,cinema_id,movie_id)
VALUES
('Spiderman: No Way Home','For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. ','Jon Watts','PG','02:00:00','Sci-Fi','2021-12-17','Zendaya,Tom Holland, enedict Cumberbatch','https://iphoneswallpapers.com/wp-content/uploads/2021/08/spiderman-no-way-home.jpg','coming soon',0,0,1,1),
('Shang-Chi and the Legend of the Ten Rings','Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.','','PG-13','02:12:00','Action','2021-09-03','Simu Liu,Awkwafina,Menger Zhang,Fala Chen,Florian Munteanu','https://www.movienewsnet.com/wp-content/uploads/2021/04/SimuLiuPoster.jpeg','coming soon',92,90,1,2),
('Black Widow','Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. ','Cate Shortland','PG-13','02:15:00','Action','2021-08-23','Scarlett Johansson,Florence Pugh,Rachel Weisz,David Harbour,Ray Winstone','https://preview.redd.it/qp6yhfw4ruv41.png?auto=webp&s=dc9b7f1758382df9d91fc6346c4aa572d97095ac','showing',80,74,1,3),
('Dune','Feature adaptation of Frank Herberts science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.','','','02:05:00','Sci-Fi','2021-09-03','Rebecca Ferguson,David Dastmalchian,Jason Momoa,Zendaya,Timothée Chalamet','https://i.pinimg.com/originals/7e/4c/3a/7e4c3a7b6aa1fe5ae34d3247f054f517.jpg','showing',0,0,1,4),
('My Hero Academia: World Heroes Mission','When a cult of terrorists ruins a city by releasing a toxin that causes peoples abilities to spiral out of control, Japans greatest heroes spread around the world in an attempt to track down the mastermind and put him to justice.','Kenji Nagasaki','PG','01:44:00','Animation','2021-08-25','Tetsu Inada,Yuki Kaji,Kenta Miyake,Nobuhiko Okamoto,Ayane Sakura','https://img1.ak.crunchyroll.com/i/spire2/a3ee3e682ea0f44666a0a8effc3dc8c11616911388_main.jpg','showing',84,83,1,5),
('Space Jam: A New Legacy','A rogue artificial intelligence kidnaps the son of famed basketball player LeBron James, who then has to work with Bugs Bunny to win a basketball game.','Malcolm D. Lee','G','01:55:00','Animation','2021-07-16','LeBron James, Don Cheadle, Cedric Joe, Sue Bird, Damian Lillard','https://posterspy.com/wp-content/uploads/2020/06/03.jpg','showing',83,87,1,6),

('Spiderman: No Way Home','For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. ','Jon Watts','PG','02:00:00','Sci-Fi','2021-12-17','Zendaya,Tom Holland, enedict Cumberbatch','https://iphoneswallpapers.com/wp-content/uploads/2021/08/spiderman-no-way-home.jpg','coming soon',0,0,2,1),
('Shang-Chi and the Legend of the Ten Rings','Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.','','PG-13','02:12:00','Action','2021-09-03','Simu Liu,Awkwafina,Menger Zhang,Fala Chen,Florian Munteanu','https://www.movienewsnet.com/wp-content/uploads/2021/04/SimuLiuPoster.jpeg','coming soon',92,90,2,2),
('Black Widow','Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. ','Cate Shortland','PG-13','02:15:00','Action','2021-08-23','Scarlett Johansson,Florence Pugh,Rachel Weisz,David Harbour,Ray Winstone','https://preview.redd.it/qp6yhfw4ruv41.png?auto=webp&s=dc9b7f1758382df9d91fc6346c4aa572d97095ac','showing',80,74,2,3),
('Dune','Feature adaptation of Frank Herberts science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.','','','02:05:00','Sci-Fi','2021-09-03','Rebecca Ferguson,David Dastmalchian,Jason Momoa,Zendaya,Timothée Chalamet','https://i.pinimg.com/originals/7e/4c/3a/7e4c3a7b6aa1fe5ae34d3247f054f517.jpg','showing',0,0,2,4),
('My Hero Academia: World Heroes Mission','When a cult of terrorists ruins a city by releasing a toxin that causes peoples abilities to spiral out of control, Japans greatest heroes spread around the world in an attempt to track down the mastermind and put him to justice.','Kenji Nagasaki','PG','01:44:00','Animation','2021-08-25','Tetsu Inada,Yuki Kaji,Kenta Miyake,Nobuhiko Okamoto,Ayane Sakura','https://img1.ak.crunchyroll.com/i/spire2/a3ee3e682ea0f44666a0a8effc3dc8c11616911388_main.jpg','showing',84,83,2,5),
('Space Jam: A New Legacy','A rogue artificial intelligence kidnaps the son of famed basketball player LeBron James, who then has to work with Bugs Bunny to win a basketball game.','Malcolm D. Lee','G','01:55:00','Animation','2021-07-16','LeBron James, Don Cheadle, Cedric Joe, Sue Bird, Damian Lillard','https://posterspy.com/wp-content/uploads/2020/06/03.jpg','showing',83,87,2,6),

('Spiderman: No Way Home','For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. ','Jon Watts','PG','02:00:00','Sci-Fi','2021-12-17','Zendaya,Tom Holland, enedict Cumberbatch','https://iphoneswallpapers.com/wp-content/uploads/2021/08/spiderman-no-way-home.jpg','coming soon',0,0,3,1),
('Shang-Chi and the Legend of the Ten Rings','Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.','','PG-13','02:12:00','Action','2021-09-03','Simu Liu,Awkwafina,Menger Zhang,Fala Chen,Florian Munteanu','https://www.movienewsnet.com/wp-content/uploads/2021/04/SimuLiuPoster.jpeg','coming soon',92,90,3,2),
('Black Widow','Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. ','Cate Shortland','PG-13','02:15:00','Action','2021-08-23','Scarlett Johansson,Florence Pugh,Rachel Weisz,David Harbour,Ray Winstone','https://preview.redd.it/qp6yhfw4ruv41.png?auto=webp&s=dc9b7f1758382df9d91fc6346c4aa572d97095ac','showing',80,74,3,3),
('Dune','Feature adaptation of Frank Herberts science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.','','','02:05:00','Sci-Fi','2021-09-03','Rebecca Ferguson,David Dastmalchian,Jason Momoa,Zendaya,Timothée Chalamet','https://i.pinimg.com/originals/7e/4c/3a/7e4c3a7b6aa1fe5ae34d3247f054f517.jpg','showing',0,0,3,4),
('My Hero Academia: World Heroes Mission','When a cult of terrorists ruins a city by releasing a toxin that causes peoples abilities to spiral out of control, Japans greatest heroes spread around the world in an attempt to track down the mastermind and put him to justice.','Kenji Nagasaki','PG','01:44:00','Animation','2021-08-25','Tetsu Inada,Yuki Kaji,Kenta Miyake,Nobuhiko Okamoto,Ayane Sakura','https://img1.ak.crunchyroll.com/i/spire2/a3ee3e682ea0f44666a0a8effc3dc8c11616911388_main.jpg','showing',84,83,3,5),
('Space Jam: A New Legacy','A rogue artificial intelligence kidnaps the son of famed basketball player LeBron James, who then has to work with Bugs Bunny to win a basketball game.','Malcolm D. Lee','G','01:55:00','Animation','2021-07-16','LeBron James, Don Cheadle, Cedric Joe, Sue Bird, Damian Lillard','https://posterspy.com/wp-content/uploads/2020/06/03.jpg','showing',83,87,3,6),

('Spiderman: No Way Home','For the first time in the cinematic history of Spider-Man, our friendly neighborhood hero is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. ','Jon Watts','PG','02:00:00','Sci-Fi','2021-12-17','Zendaya,Tom Holland, enedict Cumberbatch','https://iphoneswallpapers.com/wp-content/uploads/2021/08/spiderman-no-way-home.jpg','coming soon',0,0,4,1),
('Shang-Chi and the Legend of the Ten Rings','Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.','','PG-13','02:12:00','Action','2021-09-03','Simu Liu,Awkwafina,Menger Zhang,Fala Chen,Florian Munteanu','https://www.movienewsnet.com/wp-content/uploads/2021/04/SimuLiuPoster.jpeg','coming soon',92,90,4,2),
('Black Widow','Natasha Romanoff, aka Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. ','Cate Shortland','PG-13','02:15:00','Action','2021-08-23','Scarlett Johansson,Florence Pugh,Rachel Weisz,David Harbour,Ray Winstone','https://preview.redd.it/qp6yhfw4ruv41.png?auto=webp&s=dc9b7f1758382df9d91fc6346c4aa572d97095ac','showing',80,74,4,3),
('Dune','Feature adaptation of Frank Herberts science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.','','','02:05:00','Sci-Fi','2021-09-03','Rebecca Ferguson,David Dastmalchian,Jason Momoa,Zendaya,Timothée Chalamet','https://i.pinimg.com/originals/7e/4c/3a/7e4c3a7b6aa1fe5ae34d3247f054f517.jpg','showing',0,0,4,4),
('My Hero Academia: World Heroes Mission','When a cult of terrorists ruins a city by releasing a toxin that causes peoples abilities to spiral out of control, Japans greatest heroes spread around the world in an attempt to track down the mastermind and put him to justice.','Kenji Nagasaki','PG','01:44:00','Animation','2021-08-25','Tetsu Inada,Yuki Kaji,Kenta Miyake,Nobuhiko Okamoto,Ayane Sakura','https://img1.ak.crunchyroll.com/i/spire2/a3ee3e682ea0f44666a0a8effc3dc8c11616911388_main.jpg','showing',84,83,4,5),
('Space Jam: A New Legacy','A rogue artificial intelligence kidnaps the son of famed basketball player LeBron James, who then has to work with Bugs Bunny to win a basketball game.','Malcolm D. Lee','G','01:55:00','Animation','2021-07-16','LeBron James, Don Cheadle, Cedric Joe, Sue Bird, Damian Lillard','https://posterspy.com/wp-content/uploads/2020/06/03.jpg','showing',83,87,4,6)
;

--SCREENING
INSERT INTO screening (available_seats, start_time, end_time, movie_date, movie_id, cinema_id)
VALUES

(18, '14:00:00', '16:55:00', '2021-08-27', 3, 1),
(27, '19:15:00', '22:00:00', '2021-08-27', 3, 1),
(27, '19:30:00', '21:45:00', '2021-08-27', 3, 1),

(27, '14:00:00', '16:55:00', '2021-08-29', 3, 1),
(27, '19:15:00', '22:00:00', '2021-08-29', 3, 1),
(27, '19:30:00', '21:45:00', '2021-08-29', 3, 1),

(27, '14:00:00', '16:55:00', '2021-08-30', 3, 1),
(27, '19:15:00', '22:00:00', '2021-08-30', 3, 1),
(27, '19:30:00', '21:45:00', '2021-08-30', 3, 1),

(27, '14:00:00', '16:55:00', '2021-08-31', 3, 1),
(27, '19:15:00', '22:00:00', '2021-08-31', 3, 1),
(27, '19:30:00', '21:45:00', '2021-08-31', 3, 1)
;

INSERT INTO screening (available_seats, start_time, end_time, movie_date, movie_id, cinema_id)
VALUES
(27, '14:45:00', ' 16:30:00', '2021-08-26', 5, 1),
(27, '18:30:00', ' 20:15:00', '2021-08-26', 5, 1),
(27, '22:15:00', ' 23:59:00', '2021-08-26', 5, 1),

(27, '14:45:00', ' 16:30:00', '2021-08-29', 5, 1),
(27, '18:30:00', ' 20:15:00', '2021-08-29', 5, 1),
(27, '22:15:00', ' 23:59:00', '2021-08-29', 5, 1),

(27, '14:45:00', ' 16:30:00', '2021-08-30', 5, 1),
(27, '18:30:00', ' 20:15:00', '2021-08-30', 5, 1),
(27, '22:15:00', ' 23:59:00', '2021-08-30', 5, 1)
;

INSERT INTO screening (available_seats, start_time, end_time, movie_date, movie_id, cinema_id)
VALUES
(27, '16:30:00', ' 18:45:00', '2021-08-27', 6, 1),
(27, '19:00:00', ' 21:15:00', '2021-08-27', 6, 1),
(27, '21:30:00', ' 23:45:00', '2021-08-27', 6, 1),

(27, '16:30:00', ' 18:45:00', '2021-08-31', 6, 1),
(27, '19:00:00', ' 21:15:00', '2021-08-31', 6, 1),
(27, '21:30:00', ' 23:45:00', '2021-08-31', 6, 1),

(27, '16:30:00', ' 18:45:00', '2021-08-31', 6, 1),
(27, '19:00:00', ' 21:15:00', '2021-08-31', 6, 1),
(27, '21:30:00', ' 23:45:00', '2021-08-31', 6, 1)
;

DELETE FROM seat;

INSERT INTO seat(seat_num, is_available, screening_id)
VALUES
('1A', true, 1), ('1B', true, 1), ('1C', true, 1), ('1D', true, 1), ('1E', true, 1), ('1F', true, 1), ('1G', true, 1), ('1H', true, 1), ('1I', true, 1),
('2A', true, 1), ('2B', true, 1), ('2C', true, 1), ('2D', true, 1), ('2E', true, 1), ('2F', true, 1), ('2G', true, 1), ('2H', true, 1), ('2I', true, 1),
('3A', true, 1), ('3B', true, 1), ('3C', true, 1), ('3D', true, 1), ('3E', true, 1), ('3F', true, 1), ('3G', true, 1), ('3H', true, 1), ('3I', true, 1),
('4A', false, 1), ('4B', false, 1), ('4C', false, 1), ('4D', false, 1), ('4E', false, 1), ('4F', false, 1), ('4G', false, 1), ('4H', false, 1), ('4I', false, 1),

('1A', false, 2), ('1B', true, 2), ('1C', true, 2), ('1D', true, 2), ('1E', true, 2), ('1F', true, 2), ('1G', true, 2), ('1H', true, 2), ('1I', false, 2),
('2A', false, 2), ('2B', true, 2), ('2C', true, 2), ('2D', true, 2), ('2E', true, 2), ('2F', true, 2), ('2G', true, 2), ('2H', true, 2), ('2I', false, 2),
('3A', false, 2), ('3B', true, 2), ('3C', true, 2), ('3D', true, 2), ('3E', true, 2), ('3F', true, 2), ('3G', true, 2), ('3H', true, 2), ('3I', false, 2),
('4A', false, 2), ('4B', false, 2), ('4C', false, 2), ('4D', false, 2), ('4E', false, 2), ('4F', false, 2), ('4G', false, 2), ('4H', false, 2), ('4I', false, 2),

('1A', false, 3), ('1B', true, 3), ('1C', true, 3), ('1D', true, 3), ('1E', true, 3), ('1F', true, 3), ('1G', true, 3), ('1H', true, 3), ('1I', false, 3),
('2A', false, 3), ('2B', true, 3), ('2C', true, 3), ('2D', true, 3), ('2E', true, 3), ('2F', true, 3), ('2G', true, 3), ('2H', true, 3), ('2I', false, 3),
('3A', false, 3), ('3B', true, 3), ('3C', true, 3), ('3D', false, 3), ('3E', false, 3), ('3F', false, 3), ('3G', true, 3), ('3H', true, 3), ('3I', false, 3),
('4A', false, 3), ('4B', false, 3), ('4C', false, 3), ('4D', false, 3), ('4E', false, 3), ('4F', false, 3), ('4G', false, 3), ('4H', false, 3), ('4I', false, 3)
;